version: 1
frontend:
  phases:
    preBuild:
      commands:
        # Set the Node.js version before installing dependencies
        - nvm use 20
        - node --version
        - npm ci
    build:
      commands:
        - npm run build
